import { theme } from "@/theme";
import { styled } from "@mui/material";
import Head from "next/head";

const Overlay = styled("main")({
  width: "100%",
  height: "100vh",
  backgroundColor: theme.palette.blue.light,
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
});

const MultiStepForm = () => {
  return (
    <>
      <Head>
        <title>Multi Step Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Overlay></Overlay>
    </>
  );
};

export default MultiStepForm;
