import Container from "../components/Container";
import { theme } from "@/theme";
import { withStyles } from "@mui/styles";
import Head from "next/head";
import { useEffect, useState } from "react";

const styles = {
  main: {
    width: "100%",
    height: "100vh",
    backgroundColor: theme.palette.blue.light,
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
};

const MultiStepForm = ({ classes }) => {
  const [isMounted, setIsMounted] = useState(false);
  useEffect(() => {
    setIsMounted(true);
  }, []);
  return (
    <>
      <Head>
        <title>Multi Step Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isMounted && (
        <main className={classes.main}>
          <Container />
        </main>
      )}
    </>
  );
};

export default withStyles(styles)(MultiStepForm);
